/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.event.KeyEvent;
import java.io.File;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Profile;
/**
 *
 * @author aravindpolepeddi
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Profile profile;
    public CreateJPanel(Profile Profiles) {
        initComponents();
        this.profile=Profiles;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelMain = new javax.swing.JPanel();
        lblBankAccNum = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblLicenseNum = new javax.swing.JLabel();
        lblVehicleIden = new javax.swing.JLabel();
        lblGeoData = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblDeviceIden = new javax.swing.JLabel();
        lblPhNum = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblFaxNum = new javax.swing.JLabel();
        lblIPAddr = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblBioMetric = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblMedicalRecNum = new javax.swing.JLabel();
        lblUIN = new javax.swing.JLabel();
        lblHealthPlanBenNum = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jTextGeoData = new javax.swing.JTextField();
        jTextPhNo = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTextFaxNo = new javax.swing.JTextField();
        jTextMedRecNo = new javax.swing.JTextField();
        jTextHealthPlanBenfNo = new javax.swing.JTextField();
        jTextBankAccNo = new javax.swing.JTextField();
        jTextLicensePlate = new javax.swing.JTextField();
        jTextVIN = new javax.swing.JTextField();
        jTextDeviceIMEI = new javax.swing.JTextField();
        jTextLinkedIn = new javax.swing.JTextField();
        jTextIPAddr = new javax.swing.JTextField();
        jTextBiometric = new javax.swing.JTextField();
        jTextPhoto = new javax.swing.JTextField();
        jButtonPhotoUpload = new javax.swing.JButton();
        jTextUIN = new javax.swing.JTextField();
        jButtonBiometricUpload = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jPanelMain.setBackground(new java.awt.Color(204, 255, 255));

        lblBankAccNum.setText("Bank account numbers");

        lblName.setText("Name");

        lblLicenseNum.setText("license number");

        lblVehicleIden.setText("Vehicle identifiers");

        lblGeoData.setText("Geographic data");

        lblDOB.setText("Date of birth");

        lblDeviceIden.setText("Device identifiers");

        lblPhNum.setText("Telephone numbers");

        lblLinkedIn.setText("LinkedIn");

        lblFaxNum.setText("FAX number");

        lblIPAddr.setText("IP Address");

        lblEmail.setText("Email addresses");

        lblBioMetric.setText("Biometric identifiers");

        lblSSN.setText("SSN");

        lblPhoto.setText("Full face photo");

        lblMedicalRecNum.setText("Medical record number");

        lblUIN.setText("unique identifying number");

        lblHealthPlanBenNum.setText("Health plan beneficiary number");

        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jTextGeoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGeoDataActionPerformed(evt);
            }
        });

        jTextPhNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPhNoActionPerformed(evt);
            }
        });
        jTextPhNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextPhNoKeyPressed(evt);
            }
        });

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jTextFaxNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFaxNoActionPerformed(evt);
            }
        });
        jTextFaxNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFaxNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFaxNoKeyReleased(evt);
            }
        });

        jTextMedRecNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMedRecNoActionPerformed(evt);
            }
        });
        jTextMedRecNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextMedRecNoKeyPressed(evt);
            }
        });

        jTextHealthPlanBenfNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHealthPlanBenfNoActionPerformed(evt);
            }
        });

        jTextBankAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBankAccNoActionPerformed(evt);
            }
        });
        jTextBankAccNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextBankAccNoKeyPressed(evt);
            }
        });

        jTextLicensePlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLicensePlateActionPerformed(evt);
            }
        });

        jTextVIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVINActionPerformed(evt);
            }
        });
        jTextVIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextVINKeyPressed(evt);
            }
        });

        jTextDeviceIMEI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDeviceIMEIActionPerformed(evt);
            }
        });
        jTextDeviceIMEI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextDeviceIMEIKeyPressed(evt);
            }
        });

        jTextLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLinkedInActionPerformed(evt);
            }
        });

        jTextIPAddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIPAddrActionPerformed(evt);
            }
        });

        jTextBiometric.setEditable(false);
        jTextBiometric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBiometricActionPerformed(evt);
            }
        });

        jTextPhoto.setEditable(false);
        jTextPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPhotoActionPerformed(evt);
            }
        });

        jButtonPhotoUpload.setText("Upload");
        jButtonPhotoUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPhotoUploadActionPerformed(evt);
            }
        });

        jTextUIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUINActionPerformed(evt);
            }
        });

        jButtonBiometricUpload.setText("Upload");
        jButtonBiometricUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBiometricUploadActionPerformed(evt);
            }
        });

        jButtonSave.setBackground(new java.awt.Color(153, 255, 153));
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        jDateChooser1.setToolTipText("");
        jDateChooser1.setDateFormatString("MM/dd/yyyy");
        jDateChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateChooser1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGeoData, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDOB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFaxNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSSN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMedicalRecNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHealthPlanBenNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBankAccNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLicenseNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVehicleIden, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDeviceIden, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLinkedIn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIPAddr, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBioMetric, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhoto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUIN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(39, 39, 39)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextHealthPlanBenfNo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextBankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextVIN, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDeviceIMEI, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIPAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jTextBiometric, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBiometricUpload))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jTextPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPhotoUpload))
                    .addComponent(jTextUIN, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextMedRecNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeoData)
                    .addComponent(jTextGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDOB)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxNum)
                    .addComponent(jTextFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalRecNum)
                    .addComponent(jTextMedRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHealthPlanBenNum)
                    .addComponent(jTextHealthPlanBenfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankAccNum)
                    .addComponent(jTextBankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNum)
                    .addComponent(jTextLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleIden)
                    .addComponent(jTextVIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceIden)
                    .addComponent(jTextDeviceIMEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedIn)
                    .addComponent(jTextLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPAddr)
                    .addComponent(jTextIPAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBioMetric)
                    .addComponent(jTextBiometric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBiometricUpload))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoto)
                    .addComponent(jTextPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPhotoUpload))
                .addGap(5, 5, 5)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUIN)
                    .addComponent(jTextUIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSave, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 251, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jTextGeoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGeoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGeoDataActionPerformed

    private void jTextPhNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPhNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPhNoActionPerformed

    private void jTextPhNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPhNoKeyPressed
        // TODO add your handling code here:
        String phoneNumber =jTextPhNo.getText();
        int length = phoneNumber.length();
        char ch=evt.getKeyChar();
        if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
            if(length<10)
            jTextPhNo.setEditable(true);
            else
            jTextPhNo.setEditable(false);
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                jTextPhNo.setEditable(true);
            }
            else{
                jTextPhNo.setEditable(false);}
        }
    }//GEN-LAST:event_jTextPhNoKeyPressed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
            
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jTextFaxNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFaxNoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFaxNoActionPerformed

    private void jTextMedRecNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMedRecNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMedRecNoActionPerformed

    private void jTextHealthPlanBenfNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHealthPlanBenfNoActionPerformed

    }//GEN-LAST:event_jTextHealthPlanBenfNoActionPerformed

    private void jTextBankAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBankAccNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBankAccNoActionPerformed

    private void jTextLicensePlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLicensePlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLicensePlateActionPerformed

    private void jTextVINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVINActionPerformed

    private void jTextDeviceIMEIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDeviceIMEIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDeviceIMEIActionPerformed

    private void jTextLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLinkedInActionPerformed

    }//GEN-LAST:event_jTextLinkedInActionPerformed

    private void jTextIPAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIPAddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIPAddrActionPerformed

    private void jTextBiometricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBiometricActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBiometricActionPerformed

    private void jTextPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPhotoActionPerformed

    private void jButtonPhotoUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPhotoUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        profile.setFull_face_photos(filename);        
        jTextPhoto.setText(filename);
    }//GEN-LAST:event_jButtonPhotoUploadActionPerformed

    private void jTextUINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUINActionPerformed

    private void jButtonBiometricUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBiometricUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        profile.setBiometric_identifiers(filename);        
        jTextBiometric.setText(filename);
    }//GEN-LAST:event_jButtonBiometricUploadActionPerformed

    private void jTextFaxNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFaxNoKeyPressed
        // TODO add your handling code here:
        String FaxNumber =jTextFaxNo.getText();
        int length = FaxNumber.length();
        int ch = evt.getKeyChar();

        if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
            if(length<10)
            jTextFaxNo.setEditable(true);
            else
            jTextFaxNo.setEditable(false);
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                jTextFaxNo.setEditable(true);
            }
            else{
                jTextFaxNo.setEditable(false);}
        }
    }//GEN-LAST:event_jTextFaxNoKeyPressed

    private void jTextFaxNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFaxNoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFaxNoKeyReleased

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        String SSN =jPasswordField1.getText();
        int length = SSN.length();
        int ch = evt.getKeyChar();

        if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
            if(length<9)
            jPasswordField1.setEditable(true);
            else
            jPasswordField1.setEditable(false);
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                jPasswordField1.setEditable(true);
            }
            else{
                jPasswordField1.setEditable(false);}
        }
        
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jTextVINKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextVINKeyPressed
        // TODO add your handling code here:
        String VIN =jTextVIN.getText();
        int length = VIN.length();
        int ch = evt.getKeyChar();

        if(length<17)
            jTextVIN.setEditable(true);
        else
            jTextVIN.setEditable(false);
        
    }//GEN-LAST:event_jTextVINKeyPressed

    private void jTextDeviceIMEIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDeviceIMEIKeyPressed
        // TODO add your handling code here:
                 String IMEI =jTextDeviceIMEI.getText();
        int length = IMEI.length();
        int ch = evt.getKeyChar();

        if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
            if(length<15)
            jTextDeviceIMEI.setEditable(true);
            else
            jTextDeviceIMEI.setEditable(false);
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                jTextDeviceIMEI.setEditable(true);
            }
            else{
                jTextDeviceIMEI.setEditable(false);}
        }
            
    }//GEN-LAST:event_jTextDeviceIMEIKeyPressed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        StringBuilder Error = new StringBuilder();
        if(jTextName.getText().isEmpty()){ Error.append("Enter Name \n");}
        else{profile.setName(jTextName.getText());}
        if(jTextGeoData.getText().isEmpty()){ Error.append("Enter Address \n");}
        else{profile.setGeographic_data(jTextGeoData.getText());}
        if(!(Pattern.matches("^\\d{10}$",jTextPhNo.getText()))|| jTextPhNo.getText().isEmpty()){ Error.append("Enter Phone Number \n");}
        else{profile.setTelephone_numbers(Long.parseLong(jTextPhNo.getText()));}
        if(jTextFaxNo.getText().isEmpty()||!(Pattern.matches("^\\d{10}$", jTextFaxNo.getText()))){ Error.append("Enter Fax Number \n");}
        else{profile.setFAX_number(Long.parseLong(jTextFaxNo.getText()));}
        if(jTextEmail.getText().isEmpty()|| !(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", jTextEmail.getText()))){ Error.append("Enter Email Address \n");}
        else{profile.setEmail_addresses(jTextEmail.getText());}
        if(!(Pattern.matches("^\\d{6}$",jTextMedRecNo.getText()))||jTextMedRecNo.getText().isEmpty()){Error.append("Enter Medical record Number \n");}
        else{profile.setMedical_record_number(jTextMedRecNo.getText());}
        if(jTextHealthPlanBenfNo.getText().isEmpty()){Error.append("Enter Health beneficiary Number \n");}
        else{profile.setHealth_plan_beneficiary_number(jTextHealthPlanBenfNo.getText());}
        if(17<jTextBankAccNo.getText().length()||jTextBankAccNo.getText().isEmpty()){Error.append("Enter Bank Account Number \n");}
        else{profile.setBank_account_numbers(Long.parseLong(jTextBankAccNo.getText()));}
        if(jTextLicensePlate.getText().isEmpty()){Error.append("Enter License Plate Number \n");}
        else{profile.setLicense_plates(jTextLicensePlate.getText());}
        if(!(Pattern.matches("^\\d{15}$",jTextDeviceIMEI.getText()))||jTextDeviceIMEI.getText().isEmpty()){Error.append("Enter Device IMEI Number \n");}
        else{profile.setDevice_identifiers(Long.parseLong(jTextDeviceIMEI.getText())); }
        if(jTextLinkedIn.getText().isEmpty()|| !(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", jTextEmail.getText()))){Error.append("Enter LinkedIn address \n");}
        else{profile.setLinkedIn(jTextLinkedIn.getText());}
        if(jTextPhoto.getText().isEmpty()){Error.append("Upload Photo  \n");}
        else{profile.setFull_face_photos(jTextPhoto.getText());}
        if(jTextBiometric.getText().isEmpty()){Error.append("Upload Biometric  \n");}
        else{profile.setBiometric_identifiers(jTextBiometric.getText());}
        if(jTextUIN.getText().isEmpty()){Error.append("Enter Unique Identifir Number \n");}
        else{profile.setUnique_identifying_num(jTextUIN.getText());}
        if(17!=jTextVIN.getText().length()||jTextVIN.getText().isEmpty()){Error.append("Enter Vehicle Identifir Number \n");}
        else{profile.setVehicle_identifiers(jTextVIN.getText());}
        if(jPasswordField1.getText().isEmpty()){Error.append("Enter Social Security Number \n");}
        else{profile.setSocial_Security_number(Long.parseLong(jPasswordField1.getText()));}
        if(jTextIPAddr.getText().isEmpty()){Error.append("Enter IP Address \n");}
        else{profile.setIP_addresses(jTextIPAddr.getText());}
        
        if(Error.isEmpty()){JOptionPane.showMessageDialog(this,"User information saved");}
        else{JOptionPane.showMessageDialog(this,Error);}
        
        
        
        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTextMedRecNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextMedRecNoKeyPressed
        // TODO add your handling code here:
        String MedRecNo =jTextMedRecNo.getText();
        int length = MedRecNo.length();
        if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
            if(length<6)
            jTextMedRecNo.setEditable(true);
            else
            jTextMedRecNo.setEditable(false);
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                jTextMedRecNo.setEditable(true);
            }
            else{
                jTextMedRecNo.setEditable(false);}
        }
    }//GEN-LAST:event_jTextMedRecNoKeyPressed

    private void jDateChooser1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooser1KeyPressed

    private void jTextBankAccNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBankAccNoKeyPressed
        // TODO add your handling code here:
        String AccNo =jTextBankAccNo.getText();
        int length = AccNo.length();
        int ch = evt.getKeyChar();

        if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
            if(length<17)
            jTextBankAccNo.setEditable(true);
            else
            jTextBankAccNo.setEditable(false);
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                jTextBankAccNo.setEditable(true);
            }
            else{
                jTextBankAccNo.setEditable(false);}
        }
    }//GEN-LAST:event_jTextBankAccNoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBiometricUpload;
    private javax.swing.JButton jButtonPhotoUpload;
    private javax.swing.JButton jButtonSave;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextBankAccNo;
    private javax.swing.JTextField jTextBiometric;
    private javax.swing.JTextField jTextDeviceIMEI;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFaxNo;
    private javax.swing.JTextField jTextGeoData;
    private javax.swing.JTextField jTextHealthPlanBenfNo;
    private javax.swing.JTextField jTextIPAddr;
    private javax.swing.JTextField jTextLicensePlate;
    private javax.swing.JTextField jTextLinkedIn;
    private javax.swing.JTextField jTextMedRecNo;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPhNo;
    private javax.swing.JTextField jTextPhoto;
    private javax.swing.JTextField jTextUIN;
    private javax.swing.JTextField jTextVIN;
    private javax.swing.JLabel lblBankAccNum;
    private javax.swing.JLabel lblBioMetric;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDeviceIden;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHealthPlanBenNum;
    private javax.swing.JLabel lblIPAddr;
    private javax.swing.JLabel lblLicenseNum;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedicalRecNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhNum;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblUIN;
    private javax.swing.JLabel lblVehicleIden;
    // End of variables declaration//GEN-END:variables
}
