/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import model.Profile;
import java.text.DateFormat; 
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author aravindpolepeddi
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Profile profile;
    public ViewJPanel(Profile Profiles){
        initComponents();
        this.profile=Profiles;
        if(profile!=null&&profile.getName()!=null&&!profile.getName().isEmpty()&&!profile.getName().isBlank()){
            try {
                viewProduct();
            } catch (MalformedURLException ex) {
                Logger.getLogger(ViewJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Enter all the fields");
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanelMain = new javax.swing.JPanel();
        lblBankAccNum = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblLicenseNum = new javax.swing.JLabel();
        lblVehicleIden = new javax.swing.JLabel();
        lblGeoData = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblDeviceIden = new javax.swing.JLabel();
        lblPhNum = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblFaxNum = new javax.swing.JLabel();
        lblIPAddr = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblMedicalRecNum = new javax.swing.JLabel();
        lblUIN = new javax.swing.JLabel();
        lblHealthPlanBenNum = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jTextGeoData = new javax.swing.JTextField();
        jTextPhNo = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTextMedRecNo = new javax.swing.JTextField();
        jTextHealthPlanBenfNo = new javax.swing.JTextField();
        jTextBankAccNo = new javax.swing.JTextField();
        jTextLicensePlate = new javax.swing.JTextField();
        jTextVIN = new javax.swing.JTextField();
        jTextDeviceIden = new javax.swing.JTextField();
        jTextLinkedIn = new javax.swing.JTextField();
        jTextIPAddr = new javax.swing.JTextField();
        jTextUIN = new javax.swing.JTextField();
        jTextFaxNo = new javax.swing.JTextField();
        jTextFieldDOB = new javax.swing.JTextField();
        jTextFieldSSN = new javax.swing.JTextField();
        jLabelBiometric = new javax.swing.JLabel();
        lblImagePhoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);

        jPanelMain.setBackground(new java.awt.Color(204, 255, 255));

        lblBankAccNum.setText("Bank account numbers");

        lblName.setText("Name");

        lblLicenseNum.setText("license number");

        lblVehicleIden.setText("Vehicle identifiers");

        lblGeoData.setText("Geographic data");

        lblDOB.setText("Date of birth");

        lblDeviceIden.setText("Device identifiers");

        lblPhNum.setText("Telephone numbers");

        lblLinkedIn.setText("LinkedIn");

        lblFaxNum.setText("FAX number");

        lblIPAddr.setText("IP Address");

        lblEmail.setText("Email addresses");

        lblSSN.setText("SSN");

        lblMedicalRecNum.setText("Medical record number");

        lblUIN.setText("unique identifying number");

        lblHealthPlanBenNum.setText("Health plan beneficiary number");

        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jTextGeoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGeoDataActionPerformed(evt);
            }
        });

        jTextPhNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPhNoActionPerformed(evt);
            }
        });
        jTextPhNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextPhNoKeyPressed(evt);
            }
        });

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jTextMedRecNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMedRecNoActionPerformed(evt);
            }
        });

        jTextHealthPlanBenfNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHealthPlanBenfNoActionPerformed(evt);
            }
        });

        jTextBankAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBankAccNoActionPerformed(evt);
            }
        });

        jTextLicensePlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLicensePlateActionPerformed(evt);
            }
        });

        jTextVIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVINActionPerformed(evt);
            }
        });

        jTextDeviceIden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDeviceIdenActionPerformed(evt);
            }
        });

        jTextLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLinkedInActionPerformed(evt);
            }
        });

        jTextIPAddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIPAddrActionPerformed(evt);
            }
        });

        jTextUIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUINActionPerformed(evt);
            }
        });

        jTextFaxNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFaxNoActionPerformed(evt);
            }
        });
        jTextFaxNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFaxNoKeyPressed(evt);
            }
        });

        jLabel2.setText("Photo");

        jLabel3.setText("Biometric");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGeoData, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDOB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFaxNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSSN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMedicalRecNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHealthPlanBenNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBankAccNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLicenseNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVehicleIden, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDeviceIden, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLinkedIn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIPAddr, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUIN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(39, 39, 39)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextHealthPlanBenfNo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextBankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextVIN, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDeviceIden, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIPAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextUIN, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFaxNo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                    .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldDOB, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextPhNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                    .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldSSN, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextMedRecNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))
                .addGap(126, 126, 126))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(lblImagePhoto))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelBiometric))
                .addGap(140, 140, 140))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeoData)
                    .addComponent(jTextGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB)
                    .addComponent(jTextFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxNum)
                    .addComponent(jTextFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalRecNum)
                    .addComponent(jTextMedRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHealthPlanBenNum)
                    .addComponent(jTextHealthPlanBenfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankAccNum)
                    .addComponent(jTextBankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNum)
                    .addComponent(jTextLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleIden)
                    .addComponent(jTextVIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceIden)
                    .addComponent(jTextDeviceIden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedIn)
                    .addComponent(jTextLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPAddr)
                    .addComponent(jTextIPAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUIN)
                    .addComponent(jTextUIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBiometric)
                    .addComponent(lblImagePhoto))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jTextGeoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGeoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGeoDataActionPerformed

    private void jTextPhNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPhNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPhNoActionPerformed

    private void jTextPhNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPhNoKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextPhNoKeyPressed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jTextMedRecNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMedRecNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMedRecNoActionPerformed

    private void jTextHealthPlanBenfNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHealthPlanBenfNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHealthPlanBenfNoActionPerformed

    private void jTextBankAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBankAccNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBankAccNoActionPerformed

    private void jTextLicensePlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLicensePlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLicensePlateActionPerformed

    private void jTextVINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVINActionPerformed

    private void jTextDeviceIdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDeviceIdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDeviceIdenActionPerformed

    private void jTextLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLinkedInActionPerformed

    private void jTextIPAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIPAddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIPAddrActionPerformed

    private void jTextUINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUINActionPerformed

    private void jTextFaxNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFaxNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFaxNoActionPerformed

    private void jTextFaxNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFaxNoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFaxNoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBiometric;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextBankAccNo;
    private javax.swing.JTextField jTextDeviceIden;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFaxNo;
    private javax.swing.JTextField jTextFieldDOB;
    private javax.swing.JTextField jTextFieldSSN;
    private javax.swing.JTextField jTextGeoData;
    private javax.swing.JTextField jTextHealthPlanBenfNo;
    private javax.swing.JTextField jTextIPAddr;
    private javax.swing.JTextField jTextLicensePlate;
    private javax.swing.JTextField jTextLinkedIn;
    private javax.swing.JTextField jTextMedRecNo;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPhNo;
    private javax.swing.JTextField jTextUIN;
    private javax.swing.JTextField jTextVIN;
    private javax.swing.JLabel lblBankAccNum;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDeviceIden;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHealthPlanBenNum;
    private javax.swing.JLabel lblIPAddr;
    private javax.swing.JLabel lblImagePhoto;
    private javax.swing.JLabel lblLicenseNum;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedicalRecNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhNum;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblUIN;
    private javax.swing.JLabel lblVehicleIden;
    // End of variables declaration//GEN-END:variables

    private void viewProduct() throws MalformedURLException {
        
          ImageIcon photo = new ImageIcon(profile.getFull_face_photos());
          Image resizedPhoto = photo.getImage().getScaledInstance(149, 151, Image.SCALE_SMOOTH);
          lblImagePhoto.setIcon(new ImageIcon(resizedPhoto));
          
          ImageIcon biometric = new ImageIcon(profile.getBiometric_identifiers());
          Image resizedBiometric = biometric.getImage().getScaledInstance(149, 151, Image.SCALE_SMOOTH);
          jLabelBiometric.setIcon(new ImageIcon(resizedBiometric));
          
          jTextUIN.setText(profile.getUnique_identifying_num());
          jTextIPAddr.setText(profile.getIP_addresses());
          jTextLinkedIn.setText(profile.getLinkedIn());
          jTextDeviceIden.setText(Long.toString(profile.getDevice_identifiers()));
          jTextVIN.setText(profile.getVehicle_identifiers());
          jTextLicensePlate.setText(Long.toString(profile.getLicense_number()));
          jTextBankAccNo.setText(Long.toString(profile.getBank_account_numbers()));
          jTextHealthPlanBenfNo.setText(profile.getHealth_plan_beneficiary_number());
          jTextMedRecNo.setText(profile.getMedical_record_number());
          jTextFieldSSN.setText(Long.toString(profile.getSocial_Security_number()));
          jTextEmail.setText(profile.getEmail_addresses());
          jTextFaxNo.setText(Long.toString(profile.getFAX_number()));
          jTextPhNo.setText(Long.toString(profile.getTelephone_numbers()));
          jTextFieldDOB.setText(String.valueOf((profile.getDate_of_birth())));
          jTextGeoData.setText(profile.getGeographic_data());
          jTextName.setText(profile.getName());
          
          
          
    }
}
